#!/usr/bin/python3
"""Defines the Movie class for representing movie records in the database.

The Movie class is an SQLAlchemy model that inherits from BaseModel and Base,
providing a structure for storing movie-related information. Each instance
of this class represents a single movie entry in the database, with various 
attributes that capture essential details like title, genres, release date,
and production information.
"""
from models.base_model import BaseModel, Base
from sqlalchemy import Column, Integer, String, Float, Text, Date, Numeric

class Movie(BaseModel, Base):
    """Representation of the Movie class.

    This class inherits from BaseModel and Base, representing a movie record
    with attributes that provide details about the movie's content, production, 
    and audience response metrics.

    Attributes:
        __tablename__ (str): Name of the table in the database ('movies').
        movie_id (int): Primary key, unique identifier for each movie.
        title (str): Title of the movie, cannot be null.
        budget (decimal): Budget of the movie.
        genres (str): Genres associated with the movie, stored as text.
        homepage (str): URL of the movie's homepage.
        keywords (str): Relevant keywords describing the movie.
        original_language (str): Language code (up to 10 characters).
        original_title (str): Original title of the movie.
        overview (str): Brief description or summary of the movie.
        popularity (float): Popularity score of the movie.
        production_companies (str): Names of production companies.
        production_countries (str): Names of countries where the movie was produced.
        release_date (date): Release date of the movie.
        revenue (decimal): Total revenue generated by the movie.
        runtime (float): Runtime of the movie in minutes.
        spoken_languages (str): Languages spoken in the movie.
        status (str): Status of the movie (e.g., "Released").
        tagline (str): Tagline or slogan of the movie.
        vote_average (float): Average user rating.
        vote_count (int): Number of votes the movie has received.
    """
    __tablename__ = 'movies'

    movie_id = Column(Integer, primary_key=True)
    title = Column(Text, nullable=False)
    budget = Column(Numeric)
    genres = Column(Text)
    homepage = Column(Text)
    keywords = Column(Text)
    original_language = Column(String(10))
    original_title = Column(Text)
    overview = Column(Text)
    popularity = Column(Float)
    production_companies = Column(Text)
    production_countries = Column(Text)
    release_date = Column(Date)
    revenue = Column(Numeric)
    runtime = Column(Float)
    spoken_languages = Column(Text)
    status = Column(String(20))
    tagline = Column(Text)
    vote_average = Column(Float)
    vote_count = Column(Integer)
